In [1]:
import tensorflow as tf

print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.9.0


In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [3]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

2022-05-17 23:11:26.707359: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [4]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.06723064,  0.65176964, -0.1351025 ,  0.6176021 , -0.22967967,
         0.37525678, -0.3676186 ,  1.0448791 , -0.15414387,  0.00257759]],
      dtype=float32)

In [5]:
tf.nn.softmax(predictions).numpy()

array([[0.07068542, 0.14507335, 0.06604704, 0.14020029, 0.06008679,
        0.1100271 , 0.05234473, 0.21493785, 0.06480131, 0.07579614]],
      dtype=float32)

In [6]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [7]:
loss_fn(y_train[:1], predictions).numpy()

2.2070286

In [8]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [9]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 12s 6ms/step - loss: 0.2919 - accuracy: 0.9151
Epoch 2/5
1875/1875 [==============================] - 12s 7ms/step - loss: 0.1417 - accuracy: 0.9582
Epoch 3/5
1875/1875 [==============================] - 11s 6ms/step - loss: 0.1052 - accuracy: 0.9683
Epoch 4/5
1875/1875 [==============================] - 12s 6ms/step - loss: 0.0877 - accuracy: 0.9732
Epoch 5/5
1875/1875 [==============================] - 12s 7ms/step - loss: 0.0750 - accuracy: 0.9767


In [10]:
model.evaluate(x_test, y_test, verbose=2)

313/313 - 2s - loss: 0.0700 - accuracy: 0.9778 - 2s/epoch - 5ms/step


[0.0700223296880722, 0.9778000116348267]

In [11]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [12]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.0906632e-08, 2.7560629e-08, 2.1876506e-06, 4.0267303e-04,
        1.2247771e-11, 9.5975572e-08, 7.7999151e-16, 9.9959379e-01,
        2.4070249e-07, 1.0916780e-06],
       [1.0803529e-08, 7.2378904e-04, 9.9926621e-01, 2.6446660e-06,
        1.0006958e-13, 5.0407252e-06, 1.2795527e-06, 1.5010759e-14,
        9.6853114e-07, 1.9453431e-14],
       [1.7635594e-07, 9.9931610e-01, 1.5688452e-04, 2.0546102e-05,
        1.1268076e-05, 4.7183439e-06, 1.0574784e-05, 3.1935991e-04,
        1.5951809e-04, 8.3363011e-07],
       [9.9891019e-01, 1.1178883e-07, 4.1682032e-04, 9.5062472e-07,
        3.5352648e-06, 6.9046670e-05, 1.7533575e-04, 3.5061665e-05,
        2.3639996e-06, 3.8655451e-04],
       [4.7366447e-07, 5.9255029e-10, 2.0957198e-06, 9.6708215e-09,
        9.9801683e-01, 3.2006827e-07, 1.6324938e-06, 2.7937707e-05,
        1.8813897e-06, 1.9488529e-03]], dtype=float32)>